env:
  global:
  - secure: en/j1ExQilUH/eufEVX+ibTU+eAZYj2GCB6U2PvM1iUeiAsQ1anzuPZQJSI3DHpT0fhGtvErcOODShRANAzcv59PRkVOcj2rMC43I6BTo8FN2M0y8r+XsigpPde1C95y5tSwr4zPz1MrZnYrhGwjmDlq9WY8KVXOTEIwVzvc66Sy0TwsQdSxPXAHnLHcX+0s75wbO9PolrE4ZSgySAoTgcdef/kjGQTrTMmcyeA8k+Mo4EytLVRZzMzfJYdcRm5UIIq0iyf+RxqSjGe0nGTFjHSpqdwCoIPGwfp6Nej413e3F1QLwT2ORTTUTWUHghk7i2JNY9NZ1N3uQU/91pIjfzfXm4ZUpSGCYe+96epyf/cV7cuJKDbNzLceB73mQqsx9kljqbvv9wn0CYjYLHqSdXP6I4ZdAI29tMwn9kEPtJJ3BvqpUse8eSkpKFcXUn4a4fjRl8trjAyxHIbw2iEOYQsWBnvuf9BcxMy14gIdByTtM+E1x5oY51jakDlGm5ezLKG+kEu6P5L/yW8D6qlhka5ZeMVfy+D7N+NAjEBsiERGuw9NsjKxjYMMRSn02PGW9eDU39gDBef4/U6/usRPvcH2gFPicbWBOVZ2f8HB7rCqmpFGQoGXQAjvsRNFNOijQBKPGERYBuSun+2SPxPJdikq/N0Zl2OyDMD7X12z1LQ=
  - secure: LdKztfxqpqlhHFlMm7xkDVLI7IstTqPeMTMwmpQJ1blrFevs680p9lX3CDveRwGvQ/COfPmc3g66D1jFSYNbTaAydwe0TCbjb4FlAwYNJ7M9sK3MMRrKxsovoinoz8q5juBOukwpdonT1ggBBNDTjnyIBIMXVkOc3jlFtMl+sUguaCe0hrJCWMzpGTKWTSRjsmzEuLqm6rsygTe8yVRIPWmfj1533vgR4hBVgsnhsHdRKRYYFiMb8EG/m1+l3Kqe4NwOIAcKERuVVFs77ceisE/iGN/vTFLywJV/d9SfxYJmB2WeaWldz77oU4DSplEt5P/d2I7RVQ/OyMgUf07MBb0NOzBRmbY/4wZ2n+qZYzQZTUP7XqOtGzyErl211B//2/KgnFZIuDVPhSmSDrxSVNdtzhL9KpAToFO/tUt0moNvhzF6gXButu3fyYVItF5kwMmOBVDTDS/M4X0OCBMDO+7w0GWedoQbTZxu2ly6HB0JQMUuK2JfRoUY0mqpM/E1el8OHQDQ2C5aW37zF6sSIs8bUwnNHL9HZ1QA91XAmIFppsA1GLb4tznChLgWv4ltRyD9eDx7a2q0rnS9v0Dc+Aaf6sqS3VViUDviXL//6Yd8aHQC3YepL2YyfPLCKO0Bb7LPybi0L3glgn+RHK4/0oTCzNH9jFqk2N8N7uO4u8M=
  - MANAGER_SH="release-manager.sh"
  - MANAGER_URL="https://raw.githubusercontent.com/3mdeb/docker-release-manager/master/release-manager.sh"
sudo: required
services:
- docker
before_script:
- wget -O $MANAGER_SH $MANAGER_URL
script:
- bash $MANAGER_SH build
after_script:
- docker images
deploy:
  skip_cleanup: true
  provider: script
  script: bash $MANAGER_SH push
  on:
    branch: master
